version: '3.9'
services:
  php-env:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - 9089:80
    depends_on:
      - db_mysql

  db_mysql:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: hellopets
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9087:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db_mysql